version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/SimpleHTTP

    steps:
      - add_ssh_keys:
          fingerprints:
            - "f5:fb:03:ab:85:8a:be:b9:a0:72:58:cb:32:7c:d0:f1"
      - run:
          name: clone shellscripts
          command: git clone git@github.com:ffmammadov/shellscripts.git
      - run:
          name: clone repo
          command: git clone git@github.com:ffmammadov/SimpleHTTP.git && cd SimpleHTTP
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build
          command: gradle build -x check

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/SimpleHTTP

    steps:
      - checkout
      - run:
          name: run tests
          command: gradle check
      - run:
          name: send test results to codecov
          command: bash <(curl -s https://codecov.io/bash)

  sonar_report:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/SimpleHTTP

    steps:
      - checkout
      - run:
          name: Send to Sonar
          command: |
            gradle sonarqube \
              -Dsonar.projectKey=ffmammadov_SimpleHTTP \
              -Dsonar.organization=ffmammadov-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=47b2f43b9a40d76a9cc2ccce8cdc6c670341fd54
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar_report:
          requires:
            - test
